/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";

export function Office(props) {
  const { nodes, materials } = useGLTF('models/scene.gltf')
  const texture = useTexture("textures/baked.png");

  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  })
  

  return (
    <group {...props} dispose={null}>
      <group position={[1.013, 1.772, -1.89]} scale={[0.461, 0.487, 0.414]}>
        <mesh geometry={nodes.Mousepad.geometry} material={materials.Mousepad} position={[-0.167, -0.036, -0.263]} rotation={[-Math.PI / 2, 0, 0]} scale={[94.831, 83.226, 1.322]} />
      </group>
      <group position={[1.328, 2.095, -1.866]} scale={[2.953, 0.735, 1.37]}>
        <mesh geometry={nodes.Mouse.geometry} material={materials['Material.002']} position={[-0.217, -0.482, -0.098]} scale={[101.051, 341.19, 209.276]} />
      </group>
      <group position={[1.198, 2.094, -2.205]} scale={[0.941, 0.735, 0.771]}>
        <mesh geometry={nodes.BassSpeakers1.geometry} material={materials.Plastic1BassSpeakers1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[2.385, 1.818, -2.043]} scale={[0.941, 0.735, 0.771]}>
        <mesh geometry={nodes.Shelf_Small2.geometry} material={materials.White} position={[0, 0, -0.318]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[0.293, 1, -0.22]} scale={[0.941, 1.294, 0.972]}>
        <mesh geometry={nodes.WoolCarpet1.geometry} material={materials.WoolCarpet1} position={[0.072, 0.026, 0.545]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[158.556, 159.04, 36.782]} />
      </group>
      <group position={[0.293, 2.653, -1.992]} scale={[0.941, 0.735, 0.771]}>
        <group position={[0.977, -0.283, -0.433]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Houseplant_2_1.geometry} material={materials.Black} />
          <mesh geometry={nodes.Houseplant_2_2.geometry} material={materials.Brown} />
          <mesh geometry={nodes.Houseplant_2_3.geometry} material={materials.DarkGreen} />
          <mesh geometry={nodes.Houseplant_2_4.geometry} material={materials.LightOrange} />
        </group>
      </group>
      <group position={[2.31, 2.594, -1.541]} scale={[2.486, 1.049, 2.101]}>
        <mesh geometry={nodes.Mug_with_office_tools.geometry} material={materials['Material.003']} position={[0.031, -0.488, -0.375]} scale={100} />
      </group>
      <group position={[0.293, 4.18, -0.191]} scale={[2.063, 0.974, 1.586]}>
        <mesh geometry={nodes.Ceiling_Fan.geometry} material={materials['Material.005']} scale={100} />
      </group>
      <group position={[0.293, 1.155, -0.22]} rotation={[Math.PI, -0.118, Math.PI]} scale={[0.93, 1.369, 1.29]}>
        <group position={[0.032, -0.104, 0.605]} rotation={[-Math.PI / 2, 0, -0.046]} scale={[137.607, 100.631, 93.322]}>
          <mesh geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
          <mesh geometry={nodes.OfficeChair_2.geometry} material={materials['Black.001']} />
          <mesh geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
        </group>
      </group>
      <group position={[-1.464, 1.036, -2.139]} rotation={[0, -1.519, 0]} scale={[0.773, 0.735, 1.652]}>
        <group position={[0.098, 1.165, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.797}>
          <mesh geometry={nodes.Draw_1.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Draw_2.geometry} material={materials.Metal_Handle} />
          <mesh geometry={nodes.Draw_3.geometry} material={materials.Sticker} />
        </group>
        <group position={[0.098, 0.794, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.797}>
          <mesh geometry={nodes.Draw001_1.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Draw001_2.geometry} material={materials.Metal_Handle} />
          <mesh geometry={nodes.Draw001_3.geometry} material={materials.Sticker} />
        </group>
        <group position={[0.098, 0.425, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.797}>
          <mesh geometry={nodes.Draw002_1.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Draw002_2.geometry} material={materials.Metal_Handle} />
          <mesh geometry={nodes.Draw002_3.geometry} material={materials.Sticker} />
        </group>
        <group position={[0.098, 0.055, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.797}>
          <mesh geometry={nodes.Draw003_1.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Draw003_2.geometry} material={materials.Metal_Handle} />
          <mesh geometry={nodes.Draw003_3.geometry} material={materials.Sticker} />
        </group>
        <mesh geometry={nodes.Main_.geometry} material={materials.Metal_1} position={[0.042, 0.592, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.797} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.673, 0.127, -0.405]} scale={[0.941, 0.735, 0.771]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-3.092, 2.25, -0.149]} rotation={[-Math.PI, 0, 0]} scale={[-0.721, -0.614, -1.711]} />
      <mesh geometry={nodes.Analog_Cock.geometry} material={materials.Mat} position={[2.351, 2.595, -2.457]} rotation={[Math.PI, -1.506, Math.PI]} scale={[0.009, 0.02, 0.025]} />
      <mesh geometry={nodes.group970697144001.geometry} material={materials['mat17.003']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh928384235001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh928384235001_1.geometry} material={materials['mat18.001']} />
      </group>
      <mesh geometry={nodes.group848587833001.geometry} material={materials['mat17.003']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh830606209001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh830606209001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh77709967001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh77709967001_1.geometry} material={materials['mat18.001']} />
        <mesh geometry={nodes.mesh77709967001_2.geometry} material={materials['mat17.003']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh765891613001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh765891613001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh491062930001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh491062930001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh451389640001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh451389640001_1.geometry} material={materials['mat18.001']} />
      </group>
      <mesh geometry={nodes.group427675855001.geometry} material={materials['mat19.001']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group298871933001.geometry} material={materials['mat17.003']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh205479027001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh205479027001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh2011576104001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh2011576104001_1.geometry} material={materials['mat18.001']} />
      </group>
      <mesh geometry={nodes.group1856349250001.geometry} material={materials['mat19.001']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1840719534001.geometry} material={materials['mat17.003']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1785529362001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh1785529362001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1774544435001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh1774544435001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1614564418001.geometry} material={materials['mat18.001']} />
        <mesh geometry={nodes.mesh1614564418001_1.geometry} material={materials['mat19.001']} />
      </group>
      <mesh geometry={nodes.group1606767967001.geometry} material={materials['mat20.001']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1512631129001.geometry} material={materials['mat17.003']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1477700025001.geometry} material={materials['mat19.001']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1246942833001.geometry} material={materials['mat20.001']} position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh11767427001.geometry} material={materials['mat19.001']} />
        <mesh geometry={nodes.mesh11767427001_1.geometry} material={materials['mat18.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1103958513001.geometry} material={materials['mat18.001']} />
        <mesh geometry={nodes.mesh1103958513001_1.geometry} material={materials['mat19.001']} />
      </group>
      <group position={[-2.364, 2.607, -0.961]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1024187379001.geometry} material={materials['mat18.001']} />
        <mesh geometry={nodes.mesh1024187379001_1.geometry} material={materials['mat19.001']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[0.322, 0.557, -0.224]} scale={[2.794, 0.193, 2.323]} />
      <mesh geometry={nodes.Cube001_Cube002.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube002_Cube003.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube003_Cube004.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube004_Cube005.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube005_Cube006.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube006_Cube007.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube007_Cube008.geometry} material={materials.GrayPlastic} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cube_Cube001.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.WhiteSteelScrew} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.BlackPlastic} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.BlackPlastic} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.WhiteSteelScrew} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.WhiteSteelScrew} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.BlackPlastic} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.BlackPlastic} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.WhiteSteelScrew} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.BlackCoatSteel} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.726, 0.772, 1.139]} />
      <mesh geometry={nodes.Plane001_Plane002.geometry} material={materials.BlackWood} position={[0.293, 1.012, -2.121]} rotation={[Math.PI, -1.548, Math.PI]} scale={[0.953, 0.772, 1.14]} />
      <group position={[-0.764, 1.674, -2.301]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={[4.124, 2.526, 1.424]}>
        <mesh geometry={nodes.computerScreen_2.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.computerScreen_2_1.geometry} material={materials.metal} />
      </group>
      <mesh geometry={nodes.Keyboard.geometry} material={materials['Mat.001']} position={[-0.141, 1.731, -2.065]} scale={[0.014, 0.011, 0.008]} />
      <group position={[-1.643, 2.938, -2.447]} scale={[0.106, 0.042, 0.306]}>
        <mesh geometry={nodes.Calender_01_Plane003_1.geometry} material={materials.FFFFFF} />
        <mesh geometry={nodes.Calender_01_Plane003_1_1.geometry} material={materials['1A1A1A']} />
        <mesh geometry={nodes.Calender_01_Plane003_1_2.geometry} material={materials['00BCD4']} />
        <mesh geometry={nodes.Calender_01_Plane003_1_3.geometry} material={materials['455A64']} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh11767427.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh11767427_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh77709967.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh77709967_1.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh77709967_2.geometry} material={materials['mat17.002']} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh205479027.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh205479027_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group298871933.geometry} material={materials['mat17.002']} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group427675855.geometry} material={materials.mat19} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh451389640.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh451389640_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh491062930.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh491062930_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh765891613.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh765891613_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh830606209.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh830606209_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group848587833.geometry} material={materials['mat17.002']} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh928384235.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh928384235_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group970697144.geometry} material={materials['mat17.002']} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1024187379.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1024187379_1.geometry} material={materials.mat19} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1103958513.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1103958513_1.geometry} material={materials.mat19} />
      </group>
      <mesh geometry={nodes.group1246942833.geometry} material={materials.mat20} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1477700025.geometry} material={materials.mat19} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1512631129.geometry} material={materials['mat17.002']} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1606767967.geometry} material={materials.mat20} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1614564418.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1614564418_1.geometry} material={materials.mat19} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1774544435.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh1774544435_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh1785529362.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh1785529362_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group1840719534.geometry} material={materials['mat17.002']} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <mesh geometry={nodes.group1856349250.geometry} material={materials.mat19} position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]} />
      <group position={[-2.364, 2.617, 0.419]} rotation={[0, 1.519, 0]} scale={[0.884, 0.956, 1.008]}>
        <mesh geometry={nodes.mesh2011576104.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh2011576104_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-1.63, 2.278, -2.288]} rotation={[Math.PI, -0.595, Math.PI]} scale={[0.631, 0.49, 0.659]}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat22} />
        <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat15} />
        <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat24} />
      </group>
      <group position={[-2.393, 2.445, 1.804]} scale={[0.483, 0.695, 0.804]}>
        <mesh geometry={nodes['Node-Mesh001'].geometry} material={materials['mat21.001']} />
        <mesh geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat15.001']} />
      </group>
      <group position={[0.268, 3.194, -2.397]} rotation={[Math.PI, -0.068, Math.PI]} scale={[0.941, 0.735, 0.772]}>
        <mesh geometry={nodes['Node-Mesh002'].geometry} material={materials.mat23} />
        <mesh geometry={nodes['Node-Mesh002_1'].geometry} material={materials['mat21.002']} />
        <mesh geometry={nodes['Node-Mesh002_2'].geometry} material={materials.mat16} />
        <mesh geometry={nodes['Node-Mesh002_3'].geometry} material={materials['mat22.001']} />
        <mesh geometry={nodes['Node-Mesh002_4'].geometry} material={materials.mat17} />
        <mesh geometry={nodes['Node-Mesh002_5'].geometry} material={materials['mat15.002']} />
        <mesh geometry={nodes['Node-Mesh002_6'].geometry} material={materials['mat24.001']} />
        <mesh geometry={nodes['Node-Mesh002_7'].geometry} material={materials.mat25} />
      </group>
      <group position={[-0.535, 3.552, -2.479]} rotation={[Math.PI, -0.094, Math.PI]} scale={[0.94, 0.735, 0.773]}>
        <mesh geometry={nodes['Node-Mesh003'].geometry} material={materials['mat23.001']} />
        <mesh geometry={nodes['Node-Mesh003_1'].geometry} material={materials['mat21.003']} />
        <mesh geometry={nodes['Node-Mesh003_2'].geometry} material={materials.mat12} />
        <mesh geometry={nodes['Node-Mesh003_3'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh003_4'].geometry} material={materials['mat24.002']} />
        <mesh geometry={nodes['Node-Mesh003_5'].geometry} material={materials['mat25.001']} />
      </group>
      <group position={[0.994, 2.873, -2.434]} rotation={[Math.PI, -0.002, Math.PI]} scale={[0.941, 0.735, 0.771]}>
        <mesh geometry={nodes['Node-Mesh004'].geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes['Node-Mesh004_1'].geometry} material={materials['mat21.004']} />
        <mesh geometry={nodes['Node-Mesh004_2'].geometry} material={materials.mat7} />
        <mesh geometry={nodes['Node-Mesh004_3'].geometry} material={materials.mat6} />
        <mesh geometry={nodes['Node-Mesh004_4'].geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes['Node-Mesh004_5'].geometry} material={materials['mat24.003']} />
        <mesh geometry={nodes['Node-Mesh004_6'].geometry} material={materials['mat25.002']} />
      </group>
      <group position={[-2.349, 1.038, 1.355]} rotation={[0.004, -0.037, 0.025]} scale={[0.522, 0.443, 0.417]}>
        <mesh geometry={nodes['Cooler_Cylinder004-Mesh'].geometry} material={materials.WhitePlastic} />
        <mesh geometry={nodes['Cooler_Cylinder004-Mesh_1'].geometry} material={materials.BluePlastic} />
        <mesh geometry={nodes['Cooler_Cylinder004-Mesh_2'].geometry} material={materials.Red} />
        <mesh geometry={nodes['Cooler_Cylinder004-Mesh_3'].geometry} material={materials.Blue} />
      </group>
      <mesh geometry={nodes.Trashbin.geometry} material={materials['Material.006']} position={[2.303, 1.044, -2.295]} scale={[94.143, 100, 100]} />
    </group>
  )
}

useGLTF.preload('models/scene.gltf')
