/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/scene.gltf");
  const texture = useTexture("textures/baked.png");

  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });
  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0);
    animate(glassTextureOpacity, section === 0 ? 1 : 0);
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
  });



  
  return (
    <group {...props} dispose={null} position={[0.50, -0.85, 0.95]} >
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode012"
        position={[2.195, 0.607, -2.606]}
        scale={[2.124, 2.045, 2.125]}
      >
        <mesh
          name="Trashbin"
          geometry={nodes.Trashbin.geometry}
          material={materials["Material.006"]}
          scale={100}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode001"
        position={[0.766, 1.654, -2.167]}
        scale={[0.489, 0.663, 0.537]}
      >
        <mesh
          name="Mousepad"
          geometry={nodes.Mousepad.geometry}
          material={materials.Mousepad}
          position={[-0.167, -0.036, -0.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[60, 45, 1.5]}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode002"
        position={[0.4, 2.093, -2]}
        scale={[3.137, 1, 1.778]}
      >
        <mesh
          name="Mouse"
          geometry={nodes.Mouse.geometry}
          material={materials["Material.002"]}
          position={[-0.2, -0.482, -0.09]}
          scale={[111.897, 579.457, 256.517]}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode003"
        position={[0.962, 2.091, -2.576]}
      >
        <mesh
          name="BassSpeakers1"
          geometry={nodes.BassSpeakers1.geometry}
          material={materials.Plastic1BassSpeakers1}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode004"
        position={[2.222, 1.716, -2.366]}
      >
        <mesh
          name="Shelf_Small2"
          geometry={nodes.Shelf_Small2.geometry}
          material={materials.White}
          position={[0, 0, -0.318]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </motion.group>
      <motion.group
        name="RootNode005"
        position={[0, 0.603, 0]}
        scale={[1, 1.761, 1.262]}
      >
        <mesh
          name="WoolCarpet1"
          geometry={nodes.WoolCarpet1.geometry}
          material={materials.WoolCarpet1}
          position={[0.072, 0.026, 0.545]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[158.556, 159.04, 36.782]}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode007"
        position={[0, 2.852, -2.3]}
      >
        <group
          name="Houseplant_2"
          position={[0.977, -0.283, -0.433]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="Houseplant_2_1"
            geometry={nodes.Houseplant_2_1.geometry}
            material={materials.Black}
          />
          <mesh
            name="Houseplant_2_2"
            geometry={nodes.Houseplant_2_2.geometry}
            material={materials.Brown}
          />
          <mesh
            name="Houseplant_2_3"
            geometry={nodes.Houseplant_2_3.geometry}
            material={materials.DarkGreen}
          />
          <mesh
            name="Houseplant_2_4"
            geometry={nodes.Houseplant_2_4.geometry}
            material={materials.LightOrange}
          />
        </group>
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode008"
        position={[2.143, 2.772, -1.714]}
        scale={[2.641, 1.428, 2.727]}
      >
        <mesh
          name="Mug_with_office_tools"
          geometry={nodes.Mug_with_office_tools.geometry}
          material={materials["Material.003"]}
          position={[0.031, -0.488, -0.375]}
          scale={100}
        />
      </motion.group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode009"
        position={[0, 4.93, 0.038]}
        scale={[2.192, 1.326, 2.059]}
      >
        <mesh
          name="Ceiling_Fan"
          geometry={nodes.Ceiling_Fan.geometry}
          material={materials["Material.005"]}
          scale={100}
        />
      </motion.group>
      <group
        name="RootNode010"
        position={[0, 0.813, 0]}
        rotation={[Math.PI, -0.118, Math.PI]}
        scale={[0.99, 1.863, 1.667]}
      >
        <group
          name="OfficeChair"
          position={[0.022, -0.12, 0.905]}
          rotation={[-Math.PI / 2, 0, -0.046]}
          scale={[105.607, 75.631, 85.322]}
        >
          <mesh
            name="OfficeChair_1"
            geometry={nodes.OfficeChair_1.geometry}
            material={materials.Grey}
          />
          <mesh
            name="OfficeChair_2"
            geometry={nodes.OfficeChair_2.geometry}
            material={materials["Black.001"]}
          />
          <mesh
            name="OfficeChair_3"
            geometry={nodes.OfficeChair_3.geometry}
            material={materials.Chair}
          />
        </group>
      </group>
      <motion.group
        animate={{
          scale: section === 0 ? 1 : 0.5,
        }}
        name="RootNode011"
        position={[-1.866, 0.651, -2.49]}
        rotation={[0, -1.519, 0]}
        scale={[1.003, 1, 1.755]}
      >
        <group
          name="Draw"
          position={[0.098, 1.165, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.797}
        >
          <mesh
            name="Draw_1"
            geometry={nodes.Draw_1.geometry}
            material={materials.Metal_1}
          />
          <mesh
            name="Draw_2"
            geometry={nodes.Draw_2.geometry}
            material={materials.Metal_Handle}
          />
          <mesh
            name="Draw_3"
            geometry={nodes.Draw_3.geometry}
            material={materials.Sticker}
          />
        </group>
        <group
          name="Draw001"
          position={[0.098, 0.794, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.797}
        >
          <mesh
            name="Draw001_1"
            geometry={nodes.Draw001_1.geometry}
            material={materials.Metal_1}
          />
          <mesh
            name="Draw001_2"
            geometry={nodes.Draw001_2.geometry}
            material={materials.Metal_Handle}
          />
          <mesh
            name="Draw001_3"
            geometry={nodes.Draw001_3.geometry}
            material={materials.Sticker}
          />
        </group>
        <group
          name="Draw002"
          position={[0.098, 0.425, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.797}
        >
          <mesh
            name="Draw002_1"
            geometry={nodes.Draw002_1.geometry}
            material={materials.Metal_1}
          />
          <mesh
            name="Draw002_2"
            geometry={nodes.Draw002_2.geometry}
            material={materials.Metal_Handle}
          />
          <mesh
            name="Draw002_3"
            geometry={nodes.Draw002_3.geometry}
            material={materials.Sticker}
          />
        </group>
        <group
          name="Draw003"
          position={[0.098, 0.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.797}
        >
          <mesh
            name="Draw003_1"
            geometry={nodes.Draw003_1.geometry}
            material={materials.Metal_1}
          />
          <mesh
            name="Draw003_2"
            geometry={nodes.Draw003_2.geometry}
            material={materials.Metal_Handle}
          />
          <mesh
            name="Draw003_3"
            geometry={nodes.Draw003_3.geometry}
            material={materials.Sticker}
          />
        </group>
        <mesh
          name="Main_"
          geometry={nodes.Main_.geometry}
          material={materials.Metal_1}
          position={[0.042, 0.592, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.797}
        />
      </motion.group>
      <group
        name="Cooler_Cylinder004"
        position={[-2.806, 0.655, 2.044]}
        rotation={[0.004, -0.037, 0.025]}
        scale={[0.555, 0.603, 0.54]}
      >
        <mesh
          name="Cooler_Cylinder004-Mesh"
          geometry={nodes["Cooler_Cylinder004-Mesh"].geometry}
          material={materials.WhitePlastic}
        />
        <mesh
          name="Cooler_Cylinder004-Mesh_1"
          geometry={nodes["Cooler_Cylinder004-Mesh_1"].geometry}
          material={materials.BluePlastic}
        />
        <mesh
          name="Cooler_Cylinder004-Mesh_2"
          geometry={nodes["Cooler_Cylinder004-Mesh_2"].geometry}
          material={materials.Red}
        />
        <mesh
          name="Cooler_Cylinder004-Mesh_3"
          geometry={nodes["Cooler_Cylinder004-Mesh_3"].geometry}
          material={materials.Blue}
        />
      </group>
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-1.026, -0.587, -0.24]}
      />
      <mesh
        name="Analog_Cock"
        geometry={nodes.Analog_Cock.geometry}
        material={materials.Mat}
        position={[2.186, 2.774, -2.904]}
        rotation={[Math.PI, -1.506, Math.PI]}
        scale={[0.011, 0.028, 0.027]}
      />
      <mesh
        name="group970697144001"
        geometry={nodes.group970697144001.geometry}
        material={materials["mat17.003"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group928384235001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh928384235001"
          geometry={nodes.mesh928384235001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh928384235001_1"
          geometry={nodes.mesh928384235001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <mesh
        name="group848587833001"
        geometry={nodes.group848587833001.geometry}
        material={materials["mat17.003"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group830606209001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh830606209001"
          geometry={nodes.mesh830606209001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh830606209001_1"
          geometry={nodes.mesh830606209001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group77709967001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh77709967001"
          geometry={nodes.mesh77709967001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh77709967001_1"
          geometry={nodes.mesh77709967001_1.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          name="mesh77709967001_2"
          geometry={nodes.mesh77709967001_2.geometry}
          material={materials["mat17.003"]}
        />
      </group>
      <group
        name="group765891613001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh765891613001"
          geometry={nodes.mesh765891613001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh765891613001_1"
          geometry={nodes.mesh765891613001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group491062930001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh491062930001"
          geometry={nodes.mesh491062930001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh491062930001_1"
          geometry={nodes.mesh491062930001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group451389640001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh451389640001"
          geometry={nodes.mesh451389640001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh451389640001_1"
          geometry={nodes.mesh451389640001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <mesh
        name="group427675855001"
        geometry={nodes.group427675855001.geometry}
        material={materials["mat19.001"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group298871933001"
        geometry={nodes.group298871933001.geometry}
        material={materials["mat17.003"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group205479027001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh205479027001"
          geometry={nodes.mesh205479027001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh205479027001_1"
          geometry={nodes.mesh205479027001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group2011576104001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh2011576104001"
          geometry={nodes.mesh2011576104001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh2011576104001_1"
          geometry={nodes.mesh2011576104001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <mesh
        name="group1856349250001"
        geometry={nodes.group1856349250001.geometry}
        material={materials["mat19.001"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1840719534001"
        geometry={nodes.group1840719534001.geometry}
        material={materials["mat17.003"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group1785529362001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1785529362001"
          geometry={nodes.mesh1785529362001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh1785529362001_1"
          geometry={nodes.mesh1785529362001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group1774544435001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1774544435001"
          geometry={nodes.mesh1774544435001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh1774544435001_1"
          geometry={nodes.mesh1774544435001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group1614564418001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1614564418001"
          geometry={nodes.mesh1614564418001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          name="mesh1614564418001_1"
          geometry={nodes.mesh1614564418001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <mesh
        name="group1606767967001"
        geometry={nodes.group1606767967001.geometry}
        material={materials["mat20.001"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1512631129001"
        geometry={nodes.group1512631129001.geometry}
        material={materials["mat17.003"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1477700025001"
        geometry={nodes.group1477700025001.geometry}
        material={materials["mat19.001"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1246942833001"
        geometry={nodes.group1246942833001.geometry}
        material={materials["mat20.001"]}
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group11767427001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh11767427001"
          geometry={nodes.mesh11767427001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          name="mesh11767427001_1"
          geometry={nodes.mesh11767427001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        name="group1103958513001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1103958513001"
          geometry={nodes.mesh1103958513001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          name="mesh1103958513001_1"
          geometry={nodes.mesh1103958513001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <group
        name="group1024187379001"
        position={[-2.822, 2.79, -0.962]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1024187379001"
          geometry={nodes.mesh1024187379001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          name="mesh1024187379001_1"
          geometry={nodes.mesh1024187379001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials["Material.004"]}
        position={[0.031, -0.001, -0.005]}
        scale={[2.968, 0.262, 3.014]}
      />
      <mesh
        name="Cube001_Cube002"
        geometry={nodes.Cube001_Cube002.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube002_Cube003"
        geometry={nodes.Cube002_Cube003.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube003_Cube004"
        geometry={nodes.Cube003_Cube004.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube004_Cube005"
        geometry={nodes.Cube004_Cube005.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube005_Cube006"
        geometry={nodes.Cube005_Cube006.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube006_Cube007"
        geometry={nodes.Cube006_Cube007.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube007_Cube008"
        geometry={nodes.Cube007_Cube008.geometry}
        material={materials.GrayPlastic}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cube_Cube001"
        geometry={nodes.Cube_Cube001.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder001"
        geometry={nodes.Cylinder001.geometry}
        material={materials.WhiteSteelScrew}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder002"
        geometry={nodes.Cylinder002.geometry}
        material={materials.BlackPlastic}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder003"
        geometry={nodes.Cylinder003.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder004"
        geometry={nodes.Cylinder004.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder005"
        geometry={nodes.Cylinder005.geometry}
        material={materials.BlackPlastic}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder006"
        geometry={nodes.Cylinder006.geometry}
        material={materials.WhiteSteelScrew}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder007"
        geometry={nodes.Cylinder007.geometry}
        material={materials.WhiteSteelScrew}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder008"
        geometry={nodes.Cylinder008.geometry}
        material={materials.BlackPlastic}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder009"
        geometry={nodes.Cylinder009.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder010"
        geometry={nodes.Cylinder010.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder011"
        geometry={nodes.Cylinder011.geometry}
        material={materials.BlackPlastic}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder012"
        geometry={nodes.Cylinder012.geometry}
        material={materials.WhiteSteelScrew}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Cylinder013"
        geometry={nodes.Cylinder013.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[0.942, 1.051, 1.21]}
      />
      <mesh
        name="Plane001_Plane002"
        geometry={nodes.Plane001_Plane002.geometry}
        material={materials.BlackWood}
        position={[0, 0.618, -2.466]}
        rotation={[Math.PI, -1.548, Math.PI]}
        scale={[1.236, 1.051, 1.211]}
      />
      <group
        name="computerScreen"
        position={[-1.123, 1.519, -2.701]}
        rotation={[-Math.PI, 0.006, -Math.PI]}
        scale={[4.38, 3.438, 1.847]}
      >
        <mesh
          name="computerScreen_2"
          geometry={nodes.computerScreen_2.geometry}
          material={materials.metalDark}
        />
        <mesh
          name="computerScreen_2_1"
          geometry={nodes.computerScreen_2_1.geometry}
          material={materials.metal}
        />
      </group>
      <mesh
        name="Keyboard"
        geometry={nodes.Keyboard.geometry}
        material={materials["Mat.001"]}
        position={[-0.46, 1.597, -2.395]}
        scale={[0.007, 0.014, 0.011]}
      />
      <group
        name="Calender_01_Plane003"
        position={[-2.056, 3.24, -2.89]}
        scale={[0.113, 0.057, 0.397]}
      >
        <mesh
          name="Calender_01_Plane003_1"
          geometry={nodes.Calender_01_Plane003_1.geometry}
          material={materials.FFFFFF}
        />
        <mesh
          name="Calender_01_Plane003_1_1"
          geometry={nodes.Calender_01_Plane003_1_1.geometry}
          material={materials["1A1A1A"]}
        />
        <mesh
          name="Calender_01_Plane003_1_2"
          geometry={nodes.Calender_01_Plane003_1_2.geometry}
          material={materials["00BCD4"]}
        />
        <mesh
          name="Calender_01_Plane003_1_3"
          geometry={nodes.Calender_01_Plane003_1_3.geometry}
          material={materials["455A64"]}
        />
      </group>
      <group
        name="group11767427"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh11767427"
          geometry={nodes.mesh11767427.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh11767427_1"
          geometry={nodes.mesh11767427_1.geometry}
          material={materials.mat18}
        />
      </group>
      <group
        name="group77709967"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh77709967"
          geometry={nodes.mesh77709967.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh77709967_1"
          geometry={nodes.mesh77709967_1.geometry}
          material={materials.mat18}
        />
        <mesh
          name="mesh77709967_2"
          geometry={nodes.mesh77709967_2.geometry}
          material={materials["mat17.002"]}
        />
      </group>
      <group
        name="group205479027"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh205479027"
          geometry={nodes.mesh205479027.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh205479027_1"
          geometry={nodes.mesh205479027_1.geometry}
          material={materials.mat18}
        />
      </group>
      <mesh
        name="group298871933"
        geometry={nodes.group298871933.geometry}
        material={materials["mat17.002"]}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group427675855"
        geometry={nodes.group427675855.geometry}
        material={materials.mat19}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group451389640"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh451389640"
          geometry={nodes.mesh451389640.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh451389640_1"
          geometry={nodes.mesh451389640_1.geometry}
          material={materials.mat18}
        />
      </group>
      <group
        name="group491062930"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh491062930"
          geometry={nodes.mesh491062930.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh491062930_1"
          geometry={nodes.mesh491062930_1.geometry}
          material={materials.mat18}
        />
      </group>
      <group
        name="group765891613"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh765891613"
          geometry={nodes.mesh765891613.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh765891613_1"
          geometry={nodes.mesh765891613_1.geometry}
          material={materials.mat18}
        />
      </group>
      <group
        name="group830606209"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh830606209"
          geometry={nodes.mesh830606209.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh830606209_1"
          geometry={nodes.mesh830606209_1.geometry}
          material={materials.mat18}
        />
      </group>
      <mesh
        name="group848587833"
        geometry={nodes.group848587833.geometry}
        material={materials["mat17.002"]}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group928384235"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh928384235"
          geometry={nodes.mesh928384235.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh928384235_1"
          geometry={nodes.mesh928384235_1.geometry}
          material={materials.mat18}
        />
      </group>
      <mesh
        name="group970697144"
        geometry={nodes.group970697144.geometry}
        material={materials["mat17.002"]}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group1024187379"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1024187379"
          geometry={nodes.mesh1024187379.geometry}
          material={materials.mat18}
        />
        <mesh
          name="mesh1024187379_1"
          geometry={nodes.mesh1024187379_1.geometry}
          material={materials.mat19}
        />
      </group>
      <group
        name="group1103958513"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1103958513"
          geometry={nodes.mesh1103958513.geometry}
          material={materials.mat18}
        />
        <mesh
          name="mesh1103958513_1"
          geometry={nodes.mesh1103958513_1.geometry}
          material={materials.mat19}
        />
      </group>
      <mesh
        name="group1246942833"
        geometry={nodes.group1246942833.geometry}
        material={materials.mat20}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1477700025"
        geometry={nodes.group1477700025.geometry}
        material={materials.mat19}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1512631129"
        geometry={nodes.group1512631129.geometry}
        material={materials["mat17.002"]}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1606767967"
        geometry={nodes.group1606767967.geometry}
        material={materials.mat20}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group1614564418"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1614564418"
          geometry={nodes.mesh1614564418.geometry}
          material={materials.mat18}
        />
        <mesh
          name="mesh1614564418_1"
          geometry={nodes.mesh1614564418_1.geometry}
          material={materials.mat19}
        />
      </group>
      <group
        name="group1774544435"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1774544435"
          geometry={nodes.mesh1774544435.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh1774544435_1"
          geometry={nodes.mesh1774544435_1.geometry}
          material={materials.mat18}
        />
      </group>
      <group
        name="group1785529362"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh1785529362"
          geometry={nodes.mesh1785529362.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh1785529362_1"
          geometry={nodes.mesh1785529362_1.geometry}
          material={materials.mat18}
        />
      </group>
      <mesh
        name="group1840719534"
        geometry={nodes.group1840719534.geometry}
        material={materials["mat17.002"]}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <mesh
        name="group1856349250"
        geometry={nodes.group1856349250.geometry}
        material={materials.mat19}
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      />
      <group
        name="group2011576104"
        position={[-2.822, 2.804, 0.829]}
        rotation={[0, 1.519, 0]}
        scale={[1.146, 1.301, 1.071]}
      >
        <mesh
          name="mesh2011576104"
          geometry={nodes.mesh2011576104.geometry}
          material={materials.mat19}
        />
        <mesh
          name="mesh2011576104_1"
          geometry={nodes.mesh2011576104_1.geometry}
          material={materials.mat18}
        />
      </group>
      <motion.group
        name="Node"
        position={[-2.042, 2.342, -2.683]}
        rotation={[Math.PI, -0.595, Math.PI]}
        scale={[0.703, 0.668, 0.79]}
      >
        <mesh
          name="Node-Mesh"
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.mat21}
        />
        <mesh
          name="Node-Mesh_1"
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.mat22}
        />
        <mesh
          name="Node-Mesh_2"
          geometry={nodes["Node-Mesh_2"].geometry}
          material={materials.mat15}
        />
        <mesh
          name="Node-Mesh_3"
          geometry={nodes["Node-Mesh_3"].geometry}
          material={materials.mat24}
        />
      </motion.group>
      <group name="Node001" position={[-2.888, 2.268, 2.566]}>
        <mesh
          name="Node-Mesh001"
          geometry={nodes["Node-Mesh001"].geometry}
          material={materials["mat21.001"]}
        />
        <mesh
          name="Node-Mesh001_1"
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={materials["mat15.001"]}
        />
      </group>
      <group
        name="Node002"
        position={[-0.026, 3.589, -2.825]}
        rotation={[Math.PI, -0.068, Math.PI]}
      >
        <mesh
          name="Node-Mesh002"
          geometry={nodes["Node-Mesh002"].geometry}
          material={materials.mat23}
        />
        <mesh
          name="Node-Mesh002_1"
          geometry={nodes["Node-Mesh002_1"].geometry}
          material={materials["mat21.002"]}
        />
        <mesh
          name="Node-Mesh002_2"
          geometry={nodes["Node-Mesh002_2"].geometry}
          material={materials.mat16}
        />
        <mesh
          name="Node-Mesh002_3"
          geometry={nodes["Node-Mesh002_3"].geometry}
          material={materials["mat22.001"]}
        />
        <mesh
          name="Node-Mesh002_4"
          geometry={nodes["Node-Mesh002_4"].geometry}
          material={materials.mat17}
        />
        <mesh
          name="Node-Mesh002_5"
          geometry={nodes["Node-Mesh002_5"].geometry}
          material={materials["mat15.002"]}
        />
        <mesh
          name="Node-Mesh002_6"
          geometry={nodes["Node-Mesh002_6"].geometry}
          material={materials["mat24.001"]}
        />
        <mesh
          name="Node-Mesh002_7"
          geometry={nodes["Node-Mesh002_7"].geometry}
          material={materials.mat25}
        />
      </group>
      <group
        name="Node003"
        position={[-0.879, 4.076, -2.931]}
        rotation={[Math.PI, -0.094, Math.PI]}
      >
        <mesh
          name="Node-Mesh003"
          geometry={nodes["Node-Mesh003"].geometry}
          material={materials["mat23.001"]}
        />
        <mesh
          name="Node-Mesh003_1"
          geometry={nodes["Node-Mesh003_1"].geometry}
          material={materials["mat21.003"]}
        />
        <mesh
          name="Node-Mesh003_2"
          geometry={nodes["Node-Mesh003_2"].geometry}
          material={materials.mat12}
        />
        <mesh
          name="Node-Mesh003_3"
          geometry={nodes["Node-Mesh003_3"].geometry}
          material={materials.mat9}
        />
        <mesh
          name="Node-Mesh003_4"
          geometry={nodes["Node-Mesh003_4"].geometry}
          material={materials["mat24.002"]}
        />
        <mesh
          name="Node-Mesh003_5"
          geometry={nodes["Node-Mesh003_5"].geometry}
          material={materials["mat25.001"]}
        />
      </group>
      <group
        name="Node004"
        position={[0.745, 3.152, -2.873]}
        rotation={[Math.PI, -0.002, Math.PI]}
      >
        <mesh
          name="Node-Mesh004"
          geometry={nodes["Node-Mesh004"].geometry}
          material={materials["mat23.002"]}
        />
        <mesh
          name="Node-Mesh004_1"
          geometry={nodes["Node-Mesh004_1"].geometry}
          material={materials["mat21.004"]}
        />
        <mesh
          name="Node-Mesh004_2"
          geometry={nodes["Node-Mesh004_2"].geometry}
          material={materials.mat7}
        />
        <mesh
          name="Node-Mesh004_3"
          geometry={nodes["Node-Mesh004_3"].geometry}
          material={materials.mat6}
        />
        <mesh
          name="Node-Mesh004_4"
          geometry={nodes["Node-Mesh004_4"].geometry}
          material={materials["mat17.001"]}
        />
        <mesh
          name="Node-Mesh004_5"
          geometry={nodes["Node-Mesh004_5"].geometry}
          material={materials["mat24.003"]}
        />
        <mesh
          name="Node-Mesh004_6"
          geometry={nodes["Node-Mesh004_6"].geometry}
          material={materials["mat25.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/scene.gltf");
